
services:
  postgres:
    image: postgres:16
    container_name: biblioteca_postgres
    restart: always

    environment:
      POSTGRES_DB: biblioteca_db
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha

    ports:
      - "5432:5432"


    volumes:
      - postgres_data:/var/lib/postgresql/data

       #Scripts SQL
      - ../database/migrations:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
